# For faceted metrics provide the name of the metric-column in config, and return a resultset of multiple columns and rows
- tables_info:
    # Name of the driver to use.
    driver: postgresql

    # Connection information.
    connection:
        host: postgres
        port: 5432
        user: postgres
        password: Postgres
        database: postgres
        sslmode: disable

    sql: >
        SELECT C.relname as table_name, T.tableowner as table_owner, pg_total_relation_size (C.oid) as table_size FROM pg_class C join pg_tables T ON (T.tablename = C .relname) WHERE T.schemaname = 'public'

    # The time between query execution. This should be set relative to the frequency
    # of expected updates and the required granularity of changes.
    interval: 1h

    # The value for our metric is in "cnt", other columns are facets (exposed as labels)
    data-field: table_size