groups:
  - name: container_alerts
    rules:
      - alert: HighContainerUsage
        expr: rate(container_cpu_usage_seconds_total{name=~".+"}[2m]) * 100 > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Высокая нагрузка контейнера {{ $labels.name }}"
          description: "Контейнер {{ $labels.name }} использует более 80% выделенной мощности CPU в течении 2 минут"
