global:
  scrape_interval:     30s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'jupyterhub'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jupyterhub:8000']

  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'netdata'          
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['netdata:19999']
